### ISSUE TITLE
layer.open 加载的form表单动态加载渲染没有效果，加了form.rend('select'); 也不行

### ISSUE THREAD

**Issue by Gaojx3542** [yelog/layui-select-multiple#9]

**Comment by yelog** [comment]
select外部是否有class为 `layui-form` 的元素包裹，layui 规定表单元素必须在 `layui-form`内才会被渲染

**Comment by Gaojx3542** [comment]
不好意思哈，是我弄错了。项目里引用的是其他的插件，病急乱投医了。。。   问题已解决O(∩_∩)O哈哈
